version: "3"

services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3030:3030"
        volumes:
            - ./dist:/app/dist
